# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./rmstale.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.AppVersion=={{ .Version }}
    binary: rmstale

archives:
  - id: rmstale
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # Use format_overrides to change the format for specific GOOSs.
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: danstis
    name: rmstale
  discussion_category_name: General
  prerelease: auto

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^(build|chore|ci|doc|docs|none|perf|refactor|skip|test)(\\(.*?\\))?:\\s?"
